### ISSUE TITLE
Global Path Planner not able to find solution (do proper lane changes) after update

### ISSUE THREAD

**Issue by TUMGEKA** [autowarefoundation/autoware.universe#5585] opened 2023-11-14 17:30 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Hey Guys in a older Version of autoware (June 2023) the following Situation was solved like this:
![image](https://github.com/autowarefoundation/autoware.universe/assets/110600488/130f9a66-ca01-4972-8dcd-4d3fcb507ccd)

Now after updating and trying the exact same start and goal position, I am getting the following error:
`[component_container_mt-35] [INFO] [1699982942.678037694] [default_ad_api.node.routing]: server call: /api/routing/set_route_points
[component_container_mt-35] [INFO] [1699982942.678220791] [default_ad_api.node.routing]: client call: /planning/mission_planning/set_route_points
[component_container-24] [INFO] [1699982942.678287139] [planning.mission_planning.mission_planner]: server call: /planning/mission_planning/set_route_points
[component_container-24] [INFO] [1699982942.678373627] [planning.mission_planning.mission_planner]: start planning route with check points: 
[component_container-24] x: 43.9343 y: 67.6709
[component_container-24] x: -48.805 y: 33.2132
[component_container-24] 
[component_container-24] [ERROR] [1699982942.679321177] [route_handler]: Failed to find a proper route!
[component_container-24]  - start checkpoint: (43.9343, 67.6709,0)
[component_container-24]  - goal checkpoint: (-48.805, 33.2132,0)
[component_container-24]  - start lane id: 24461
[component_container-24]  - goal lane id: 26908
[component_container-24] 
[component_container-24] [WARN] [1699982942.679330758] [planning.mission_planning.mission_planner]: Failed to plan route.
[component_container-24] [INFO] [1699982942.679353695] [planning.mission_planning.mission_planner]: server exit: /planning/mission_planning/set_route_points
[component_container_mt-35] [INFO] [1699982942.679418727] [default_ad_api.node.routing]: client exit: /planning/mission_planning/set_route_points
[component_container_mt-35] [INFO] [1699982942.679430471] [default_ad_api.node.routing]: server exit: /api/routing/set_route_points
[service_log_checker-2] [ERROR] [1699982942.679431170] [system.service_log_checker]: /planning/mission_planning/set_route_points: status code 3 'The planned route is empty.' (/planning/mission_planning/mission_planner)
[service_log_checker-2] [ERROR] [1699982942.679496426] [system.service_log_checker]: /planning/mission_planning/set_route_points: status code 3 'The planned route is empty.' (/default_ad_api/node/routing)
[service_log_checker-2] [ERROR] [1699982942.679536886] [system.service_log_checker]: /api/routing/set_route_points: status code 3 'The planned route is empty.' (/default_ad_api/node/routing)
[routing_adaptor-38] [INFO] [1699982942.679536917] [default_ad_api.helpers.routing_adaptor]: client exit: /api/routing/set_route_points
[service_log_checker-2] [ERROR] [1699982942.679595503] [system.service_log_checker]: /api/routing/set_route_points: status code 3 'The planned route is empty.' (/default_ad_api/helpers/routing_adaptor)
`

It seems like the global path planner got worse doing lane changes. 

### Expected behavior

The Path planner should be able to reach the destination by doing a lange change.

### Actual behavior

The planner cannot find a proper route

### Steps to reproduce

1. Load Town10HD here: https://bitbucket.org/carla-simulator/autoware-contents/src/master/
2. Start planning sim
3. Set start Position:  Frame:map, Position(43.9343, 67.6709, 0), Orientation(0, 0, 0.999993, 0.0036383) = Angle: 3.13432
4. Set Goal Position Frame:map, Position(-48.805, 33.2132, 0), Orientation(0, 0, -0.707468, 0.706745) = Angle: -1.57182

**Comment by zulfaqar-azmi-t4** [comment] 2023-11-17 05:07
@TUMGEKA 
Thank you very much for the report. 
Based on the observation, chances are it is not the lane change module issue but more on route set when placing the goal issue.

Let me check this and get back to you once we found out the root cause.

**Comment by nourhanMohamed0** [comment] 2023-12-01 22:18
Hi i'm using Autoware.universe and i followed the steps of installing autoware from documentation and in last video in launching when i determine the goal using 2D pose Goal it gives me in terminal like this : [component_container-24] [ERROR] [1701464195.571239563] [route_handler]: Failed to find a proper route!
[component_container-24]  - start checkpoint: (3664.01, 73748,0)
[component_container-24]  - goal checkpoint: (3698.31, 73758,0)
[component_container-24]  - start lane id: 159
[component_container-24]  - goal lane id: 118
[component_container-24] 
[component_container-24] [WARN] [1701464195.571274008] [planning.mission_planning.mission_planner]: Failed to plan route.
[component_container-24] [INFO] [1701464195.571332069] [planning.mission_planning.mission_planner]: server exit: /planning/mission_planning/set_route_points
[component_container_mt-35] [INFO] [1701464195.571466123] [default_ad_api.node.routing]: client exit: /planning/mission_planning/set_route_points
[component_container_mt-35] [INFO] [1701464195.571466774] [default_ad_api.node.routing]: server exit: /api/routing/set_route_points
[service_log_checker-2] [ERROR] [1701464195.571451926] [system.service_log_checker]: /planning/mission_planning/set_route_points: status code 3 'The planned route is empty.' (/planning/mission_planning/mission_planner)
[service_log_checker-2] [ERROR] [1701464195.571592293] [system.service_log_checker]: /planning/mission_planning/set_route_points: status code 3 'The planned route is empty.' (/default_ad_api/node/routing)
[service_log_checker-2] [ERROR] [1701464195.571638080] [system.service_log_checker]: /api/routing/set_route_points: status code 3 'The planned route is empty.' (/default_ad_api/node/routing)

and car is not moving .. then what should i do ?

**Comment by zulfaqar-azmi-t4** [comment] 2023-12-05 12:23
@TUMGEKA 

I have checked the route handler and the mission planner, and there are no known changes that might have caused the issue.

I took a look at the Town10HD map itself, and it seems to me that the map may not be compliant with Autoware requirements (https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LinestringTagging.md).

Note: I had to use third-party apps to change load the map, to allow me to be able to load the map in the vector map builder.

As this issue is related to the map, rather than Autoware, I would suggest that you edit the map itself based on the tagging described in the Lanelet2 documentation.

**Comment by zulfaqar-azmi-t4** [comment] 2023-12-05 12:25
@nourhanMohamed0 

Sorry for the late response. The error message is not so clear, so sorry for that. Can you provide more detail or video of how you place the ego vehicle and the goal? At the moment, at least for the `Town10HD`, i am able to do lane following.

**Comment by nourhanMohamed0** [comment] 2023-12-05 23:09
@zulfaqar-azmi-t4 
no problem at all , the issue was solved thank you❤️

**Comment by VietPT3502** [comment] 2023-12-14 09:37
> @TUMGEKA
> 
> I have checked the route handler and the mission planner, and there are no known changes that might have caused the issue.
> 
> I took a look at the Town10HD map itself, and it seems to me that the map may not be compliant with Autoware requirements (https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LinestringTagging.md).
> 
> Note: I had to use third-party apps to change load the map, to allow me to be able to load the map in the vector map builder.
> 
> As this issue is related to the map, rather than Autoware, I would suggest that you edit the map itself based on the tagging described in the Lanelet2 documentation.

Hello, which third-party apps did you use to change load the map. Can you share detail about that.

**Comment by zulfaqar-azmi-t4** [comment] 2024-01-17 03:17
@VietPT3502 
Hi, I'm using `josm`.

**Comment by zulfaqar-azmi-t4** [comment] 2024-01-17 03:21
@TUMGEKA 
May I know what is the status for this issue?
I would suggest to create a new map/modify the map so that it is compliant with how autoware expectation.

I will close this issue for now. But if your map modification also doesn't work, the please feel free to re-open this issue.

**Closed by zulfaqar-azmi-t4** 2024-01-17 03:21 UTC
Labels: type:bug
