### ISSUE TITLE
behavior_path_planner creates shift point outside drivable area

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#2208] opened 2022-11-03 07:33 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

`behavior_path_planner` creates a shift point outside drivable area while avoiding the obstacle.

![Screenshot from 2022-11-07 11-06-26](https://user-images.githubusercontent.com/32412808/200259366-b0df4445-e7db-4ca6-b826-c37fd9708692.png)

### Expected behavior

The shift points behavior_path_planner creates must always be inside drivable area.

### Actual behavior

In some cases the shift point comes out of the drivable area.

### Steps to reproduce

1. Download isuzu_vehicle_launch in [here]( https://drive.google.com/drive/folders/1bkxamrkKsbP3J5339GVf5yKhJL0iii4l)
2. Download [test.zip](https://github.com/autowarefoundation/autoware.universe/files/9926299/test.zip)
3. Change `publish_debug_marker` parameter to true in avoidance.param.yaml 
4. run `ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=isuzu_vehicle \ scenario:=/scenario/path/test.yaml \  architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true`

**Comment by maxime-clem** [comment] 2022-11-04 01:31
Can you try this PR: https://github.com/autowarefoundation/autoware.universe/pull/2196 ? I think it will fix this issue.

**Comment by mehmetdogru** [comment] 2022-11-04 05:41
@beyzanurkaya 

Could you please add some screenshots or videos explains the issue?

**Comment by beyzanurkaya** [comment] 2022-11-08 07:09
> Can you try this PR: #2196 ? I think it will fix this issue.

I already created a PR for this issue actually.

**Comment by mehmetdogru** [comment] 2022-12-05 15:01
I will close the issue since I was not able to reproduce it anymore.

**Closed by mehmetdogru** 2022-12-05 15:01 UTC
Labels: high priority, planning
