### ISSUE TITLE
planning mode doesn't change if lane change path can't be executed in behavior path planner

### ISSUE THREAD

**Issue by alanmengg** [autowarefoundation/autoware.universe#1329] opened 2022-07-13 03:06 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

In lane driving, if vehicle in lane change mode and lane change can't successfully executed such as obstacle blocks the lane change path,  it would suck with it.
![Screenshot from 2022-07-13 10-16-04](https://user-images.githubusercontent.com/104343391/178638914-f3eb3958-c989-41b9-b977-547db1bb1532.png)
![Screenshot from 2022-07-13 10-16-44](https://user-images.githubusercontent.com/104343391/178638912-68eca747-ebb4-4c64-9c67-07e221d3f8bb.png)

### Expected behavior

if lane change can't be executed because of the obstacle, it should change to obstacle avoidance mode to plan a new path.
if planning mode change to obstacle avoidance, it can plan a new path to execute like below.
![Screenshot from 2022-07-13 10-19-56](https://user-images.githubusercontent.com/104343391/178639090-122f44cd-c6a0-4f49-9f34-249dffbb1d69.png)

### Actual behavior

it suck with lane change path and doesn't plan new path.

### Steps to reproduce

like the picture uploaded above, put some obstacle around road,  make vehicle start and goal in different lane.

### Versions

1.OS: Ubuntun 20.04
2.ROS2: Galactic
3.Autoware: Autoware.universe:main

**Comment by BonoloAWF** [comment] 2022-07-14 14:45
Duplicate of https://github.com/autowarefoundation/autoware.universe/issues/1328

**Closed by BonoloAWF** 2022-07-14 14:45 UTC
