### ISSUE TITLE
Turning radius is too short on curves

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#1759] opened 2022-09-01 07:01 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Trajectory from motion planner is outside the drivable area as in the figure below

![Screenshot from 2022-09-01 09-48-34](https://user-images.githubusercontent.com/32412808/187850450-03a47fec-6c4a-4eea-8f1e-77529574e1bb.png)

### Expected behavior

A path outside the drivable area should not have occurred.

### Actual behavior

Motion planner output is outside of drivable area.

### Steps to reproduce

1. Download [1759.zip](https://github.com/autowarefoundation/autoware.universe/files/9469755/1759.zip)
2. Download isuzu_vehicle_launch in [here]( https://drive.google.com/drive/folders/1bkxamrkKsbP3J5339GVf5yKhJL0iii4l)
3. Put isuzu_vehicle_launch in autoware.universe/vehicle directory and compile this package with `colcon build`
4. Change pcd and lanelet2 maps file path in yaml file
5. run `ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=isuzu_vehicle \
scenario:=/scenario/path/1759.yaml \
architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true`

6. Add `/planning/scenario_planning/lane_driving/trajectory` topic in rviz

7. When you run the scenario, you'll see trajectory is outside drivable area.

**Comment by maxime-clem** [comment] 2022-09-02 09:36
I was able to reproduce the issue using the planning simulator with the latest autoware (https://github.com/autowarefoundation/autoware/commit/44c70d33825617b56d8de5e6fe921000238238bd).
![image](https://user-images.githubusercontent.com/78338830/188110667-e13a9aca-1c9c-4f62-8152-71a273b8b790.png)
I will investigate possible solutions.

**Comment by maxime-clem** [comment] 2022-09-06 02:42
The main issue seems to be the road being too narrow for the dimensions of the vehicle, making it impossible to follow the road while keeping the footprint of the vehicle inside the lane.

**The solution I found is to expand the drivable area**, i.e., the space where the `obstacle_avoidance_planner` can do motion planning.
The drivable area is generated by the `behavior_path_planner` which has parameters to enable expanding the drivable area and to set the left and right expansion distance.
https://github.com/autowarefoundation/autoware.universe/blob/a4078bdf374fc617f5be531e50e892aefbbc53e0/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml#L4-L6

Changing these parameters to the following values allow to drive in the narrow curve.
```yaml
      expand_drivable_area: true
      right_bound_offset: 0.0
      left_bound_offset: 1.0
```
These parameters cannot be changed dynamically and have to be changed in the parameter file loaded at launch time.

https://user-images.githubusercontent.com/78338830/188535432-64aafd69-0da7-4077-b274-e157b6cb906e.mp4

In the video, the following extra topics are shown:
- `DrivableArea` (`/planning/scenario_planning/lane_driving/behavior_planning/path`) with color scheme "costmap".
- `DebugMarkers` (`/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/marker`) only for namespace "mpt_footprints".

**Comment by mehmetdogru** [comment] 2022-09-06 14:55
@maxime-clem 

Thank you for the solution you proposed!

There is one problem related to this approach. If there is an obstacle around and `path_planner/avoidance` module is registered then expanded drivable_area wouldn't be published for mpt to optimize the motion plan since drivable_area is expanded only in `path_planner/lane_following` module.

I will create a separate issue about it. I guess we can close this issue.

**Comment by xmfcx** [comment] 2022-09-06 16:46
> There is one problem related to this approach. If there is an obstacle around and path_planner/avoidance module is registered then expanded drivable_area wouldn't be published for mpt to optimize the motion plan since drivable_area is expanded only in path_planner/lane_following module.

@mehmetdogru can you explain again, @maxime-clem doesn't understand about this worry.

**Comment by maxime-clem** [comment] 2022-09-07 04:54
I opened a discussion about dynamically expanding the drivable area: https://github.com/orgs/autowarefoundation/discussions/2851

**Comment by mehmetdogru** [comment] 2022-09-07 09:25
@xmfcx @maxime-clem 

Sorry for not being clear.

I will attach a video here that explains my worry. 

You can see here clearly that when `path_planner/avoidance` module active (it means there are obstracles around/in the lane) drivable_area is not expanded. That is because drivable_area is extended only in `path_planner/lane_following` module except for some lane_changing cases.

As @maxime-clem suggested implementing a dynamic expansion _not depending on the path_planner modules_ would solve this issue. We can disscuss further in the disscussion.

https://user-images.githubusercontent.com/48479081/188827600-4590d028-34fd-4d2f-9db0-58f80b161c5b.mp4

**Comment by TakaHoribe** [comment] 2022-09-08 05:07
@takayuki5168 Could you check this problem? Seems the Drivable Area generation does not have consistency between behavior_path_planner modules.

**Comment by takayuki5168** [comment] 2022-09-08 10:50
@mehmetdogru 
Static expansion of drivable area is only implemented in lane_following for now.
By implementing it in other modules, you can use the static expansion in any module.

https://github.com/autowarefoundation/autoware.universe/blob/487264478af006e7745b55917b97c5f7d0c6de17/planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp#L140-L157

**Comment by mitsudome-r** [comment] 2022-09-13 08:20
I think we can discuss the original issue in this discussion: https://github.com/autowarefoundation/autoware/discussions/2851
and @maxime-clem will create a new issue regarding inconsistent drivable area parameter. After the new issue is created, I will close this issue.

**Comment by maxime-clem** [comment] 2022-09-13 09:14
I opened the follow-up issue https://github.com/autowarefoundation/autoware.universe/issues/1854

**Closed by maxime-clem** 2022-09-13 09:14 UTC
Labels: bug, high priority, planning
