### ISSUE TITLE
tf2_autoware_auto_msgs.hpp:60:13: error: redefinition of ‘void tf2::doTransform(const T&, T&, const TransformStamped&) [with T = geometry_msgs::msg::Point32_<std::allocator<void> >; geometry_msgs::msg::TransformStamped = geometry_msgs::msg::TransformStamped_<std::allocator<void> >]’

### ISSUE THREAD

**Issue by L-Net-1992** [autowarefoundation/autoware.universe#5128] opened 2023-09-26 02:01 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

![截图 2023-09-26 09-56-09](https://github.com/autowarefoundation/autoware.universe/assets/88867460/80192bd1-8b9e-4227-a119-113c0a63d7c4)

### Expected behavior

build error

### Actual behavior

build error

### Steps to reproduce

1.vcs import src < autoware.repos
2.vcs pull src
3.source /opt/ros/humble/setup.bash
4.rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
5.colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

### Versions

Ubuntu22.04
Humble
46f871fdc6df53f9dce615ce8a132e3d3d139c14

**Comment by SakodaShintaro** [comment] 2023-09-26 02:08
The same error occurs in my environment.
This is caused by a recent update to ros2/geometry2.
https://github.com/ros2/geometry2/compare/4597504ef9138f780c877f7b83b1f7fcd806dc34...a73160df358c52d1f506fce21f15f8243e9b87f4

There are pull requests created by wep21-san to deal with this issue. I hope this information is helpful.
https://github.com/autowarefoundation/autoware.universe/pull/5127
https://github.com/autowarefoundation/autoware.universe/pull/5089

**Comment by L-Net-1992** [comment] 2023-09-26 03:47
@SakodaShintaro I feel that there are some dependencies besides issues. You see, the underlying dependencies are ROS2, which should be version updates, and some are bug free. Because this package has not been updated for two months.

**Comment by SakodaShintaro** [comment] 2023-09-27 04:47
Yes, I agree that Autoware has various problems around package versioning.
If you have any good ideas, please feel free to suggest them on the [discussion page](https://github.com/orgs/autowarefoundation/discussions).

In my understanding,  this issue has been resolved since the pull request was merged.
If the problem still remains, please re-open.

**Closed by SakodaShintaro** 2023-09-27 04:47 UTC
