### ISSUE TITLE
Poor dummy pointcloud on planning simulator

### ISSUE THREAD

**Issue by yukkysaito** [autowarefoundation/autoware.universe#874] opened 2022-05-09 15:43 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

![image](https://user-images.githubusercontent.com/8327598/167446204-662c4fc1-c057-4861-8fbc-2ab8e07bed1f.png)

Pointcloud should have some vertical layers, but, in the latest version, it has only 1 layer.

### Expected behavior

https://github.com/autowarefoundation/autoware.universe/pull/527#pullrequestreview-955895269

### Actual behavior

Pointcloud should have some vertical layers, but, in the latest version, it has only 1 layer.

### Steps to reproduce

1. launch planning simulator on following tutorials.
2. add dummy car or pedestrian

**Comment by yukkysaito** [comment] 2022-05-09 15:43
cc @HiroIshida

**Comment by mitsudome-r** [comment] 2022-05-10 08:15
@yukkysaito Is anyone from TIER IV going to work on this? If so, please assign this issue to the person.

**Comment by HiroIshida** [comment] 2022-05-10 09:49
@yukkysaito 
As for vertical layers, I will check and fix this if the issue is caused by https://github.com/autowarefoundation/autoware.universe/pull/527#pullrequestreview-955895269

@taikitanaka3 
```
dummy object's shape is also strange too.
```
Is that caused because the pointcloud is generated one side of the car, instead of all around the car? If so, it is intended behavior of my past PR.

**Closed** 2022-05-11 02:00 UTC
Labels: bug
